services:
  savefw-db:
    image: postgis/postgis:18-3.6
    container_name: savefw-db
    network_mode: "host"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password # TODO: Change this
      POSTGRES_DB: savefw
    volumes:
      - postgres_data:/var/lib/postgresql

  savefw-db-gui:
    image: dbeaver/cloudbeaver:latest
    container_name: savefw-db-gui
    network_mode: "host"
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    depends_on:
      - savefw-db

  valhalla:
    image: ghcr.io/nilsnolde/docker-valhalla/valhalla:latest
    container_name: savefw_valhalla
    network_mode: "host"
    environment:
      - tile_urls=https://download.geofabrik.de/north-america/us/indiana-latest.osm.pbf https://download.geofabrik.de/north-america/us/ohio-latest.osm.pbf https://download.geofabrik.de/north-america/us/michigan-latest.osm.pbf https://download.geofabrik.de/north-america/us/illinois-latest.osm.pbf https://download.geofabrik.de/north-america/us/kentucky-latest.osm.pbf
      - build_admins=True
      - build_time_zones=True
      - build_elevation=False
      - build_tar=True
      - force_rebuild=False
      - server_threads=4
    volumes:
      - ./infra/valhalla/custom_files:/custom_files
      - ./infra/valhalla/osm:/osm:ro
    restart: unless-stopped

  savefw-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: savefw-app
    network_mode: "host"
    environment:
      - ConnectionStrings__DefaultConnection=Host=127.0.0.1;Database=savefw;Username=postgres;Password=password
      - ASPNETCORE_URLS=http://0.0.0.0:80
    depends_on:
      - savefw-db

volumes:
  postgres_data:
  cloudbeaver_data:
