services:
  savefw-db:
    image: postgis/postgis:18-3.5
    container_name: savefw-db
    network_mode: "host"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password # TODO: Change this
      POSTGRES_DB: savefw
    volumes:
      - postgres_data:/var/lib/postgresql

  savefw-db-gui:
    image: dbeaver/cloudbeaver:latest
    container_name: savefw-db-gui
    network_mode: "host"
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    depends_on:
      - savefw-db

  savefw-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: savefw-app
    network_mode: "host"
    environment:
      - ConnectionStrings__DefaultConnection=Host=127.0.0.1;Database=savefw;Username=postgres;Password=password
      - ASPNETCORE_URLS=http://0.0.0.0:80
    depends_on:
      - savefw-db

volumes:
  postgres_data:
